### Add a new item
POST http://localhost:3000/items
Content-Type: application/json

{
    "name": "Jane Doe",
    "public": "true",
    "listing": {
        "description": "This is a test listing"
    }
}

### Get all items
GET http://localhost:3000/items

### Get a single item
GET http://localhost:3000/items/1

### Update an item
PATCH http://localhost:3000/items/1
Content-Type: application/json

{
    "public": "false"
}

### Delete an item
DELETE http://localhost:3000/items/1