### Add a new item
POST http://localhost:3000/items
Content-Type: application/json

{
    "name": "Jane Doe3",
    "public": "true",
    "listing": {
        "description": "This is a test listing"
    },
    "tags": [
        {
            "content" : "tag1"
        },
        {
            "content" : "tag2"
        }
    ]
}

### Get all items
GET http://localhost:3000/items

### Get a single item
GET http://localhost:3000/items/5

### Update an item
PATCH http://localhost:3000/items/5
Content-Type: application/json

{
    "public": "false",
    "comments": [
        {
            "content": "This is a test comment"
        },
         {
            "content": "This is a test comment2"
        }
    
    ]
}

### Delete an item
DELETE http://localhost:3000/items/1